apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pihole
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: pihole-unbound
  sources:
    - repoURL: 'git@github.com:davidcardoso-homelab/pihole-unbound.git'
      targetRevision: main
      path: pihole/values/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: pihole-unbound
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
