apiVersion: batch/v1
kind: CronJob
metadata:
  name: unbound-update-root-hints
spec:
  schedule: "0 3 * * *" # Executa todo dia às 3h da manhã
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: downloader
              image: alpine:latest
              command:
                - /bin/sh
                - -c
                - |
                  apk add --no-cache unbound curl &&
                  curl -o /data/root.hints https://www.internic.net/domain/named.cache &&
                  unbound-anchor -a /data/root.key
              volumeMounts:
                - name: unbound-data
                  mountPath: /data
          restartPolicy: OnFailure
          volumes:
            - name: unbound-data
              persistentVolumeClaim:
                claimName: unbound-pvc
