apiVersion: batch/v1
kind: CronJob
metadata:
  name: unbound-update-root-hints
spec:
  schedule: "0 3 * * *" # Executa todo dia às 3h da manhã
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: unbound-cronjob
          containers:
            - name: updater
              image: bitnami/kubectl:latest
              command:
                - /bin/sh
                - -c
                - |
                  set -e

                  echo "Restarting Unbound deployment..."

                  kubectl rollout restart deployment unbound -n pihole-unbound

              volumeMounts:
                - name: unbound-data
                  mountPath: /data

          restartPolicy: OnFailure

          volumes:
            - name: unbound-data
              persistentVolumeClaim:
                claimName: unbound-pvc