apiVersion: v1
kind: PersistentVolume
metadata:
  name: unbound-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-path
  hostPath:
    path: /volumes/ssd/k3s/unbound
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: unbound-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: unbound-pv